# Generated by Django 4.2.2 on 2023-11-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipousuario', models.AutoField(db_column='Id_Tipo_Usuario', primary_key=True, serialize=False, verbose_name='Id Tipo Usuario')),
                ('tipoUsuario', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente del Vehiculo')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca del Vehiculo')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo  del Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_usuario')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
                ('password_usuario', models.CharField(max_length=50, verbose_name='Password del Usuario')),
                ('tipoUusario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
    ]
