# Generated by Django 4.2.2 on 2023-12-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='nombre_usuario_dueño',
        ),
        migrations.AddField(
            model_name='viaje',
            name='nombre_usuario_duenno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario', to_field='nombre_usuario', verbose_name='Nombre Dueño'),
        ),
    ]
