# Generated by Django 4.2.2 on 2023-12-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False, verbose_name='id_viaje')),
                ('inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('termino', models.CharField(blank=True, max_length=50, null=True)),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('patente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
    ]
