# Generated by Django 4.2.2 on 2023-11-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoUusario',
            new_name='tipoUsuario',
        ),
    ]
