# Generated by Django 4.2.6 on 2023-10-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_nombre_usuario_usuario_password_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50, verbose_name='Nombre del Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_usuario',
            field=models.CharField(max_length=50, verbose_name='Password del Usuario'),
        ),
    ]
