# Generated by Django 4.2.2 on 2023-12-02 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vehiculo_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='nombre_usuario',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario', to_field='nombre_usuario'),
        ),
    ]
