# Generated by Django 4.2.6 on 2023-10-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente del Vehiculo')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca del Vehiculo')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo del Vehiculo')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria del Vehiculo')),
            ],
        ),
    ]
